name: 'Update README'

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

jobs:
  recent-activity:
    name: 'Update README with latest activity'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/Checkout@v3
      - name: 'Update README.md from TEMPLATE.md'
        uses: RevoluzionEcosystem/RevoluzionEcosystem@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CONFIG_FILE: 'action.yml'
